//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adaptability
    {
        public int breedID { get; set; }
        public int overall { get; set; }
        public int apartment { get; set; }
        public int noviceOwners { get; set; }
        public int sensitivity { get; set; }
        public int alone { get; set; }
        public int coldWeather { get; set; }
        public int hotWeather { get; set; }
    
        public virtual OverallInformation OverallInformation { get; set; }
    }
}
