//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogProjectMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DogProjectEntities : DbContext
    {
        public DogProjectEntities()
            : base("name=DogProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adaptability> Adaptabilities { get; set; }
        public virtual DbSet<Exercise> Exercises { get; set; }
        public virtual DbSet<Friendliness> Friendlinesses { get; set; }
        public virtual DbSet<Health> Healths { get; set; }
        public virtual DbSet<OverallInformation> OverallInformations { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<DogInfo> DogInfoes { get; set; }
        public virtual DbSet<Medical> Medicals { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
