//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public int breedID { get; set; }
        public int overall { get; set; }
        public int energyLevel { get; set; }
        public int intensity { get; set; }
        public int exerciseNeed { get; set; }
        public int playfulness { get; set; }
    
        public virtual OverallInformation OverallInformation { get; set; }
    }
}
