//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendliness
    {
        public int breedID { get; set; }
        public int overall { get; set; }
        public int withFamily { get; set; }
        public int withKids { get; set; }
        public int otherDogs { get; set; }
        public int towardStrangers { get; set; }
    
        public virtual OverallInformation OverallInformation { get; set; }
    }
}
