//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public string locationName { get; set; }
        public int zipCode { get; set; }
        public string typeOfLoc { get; set; }
        public Nullable<int> aveRate { get; set; }
    
        public virtual Rating Rating { get; set; }
    }
}
