//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverallInformation
    {
        public int breedID { get; set; }
        public string breed { get; set; }
        public int adaptability { get; set; }
        public int friendliness { get; set; }
        public int health { get; set; }
        public int grooming { get; set; }
        public int training { get; set; }
        public int exercise { get; set; }
    
        public virtual Adaptability Adaptability1 { get; set; }
        public virtual Exercise Exercise1 { get; set; }
        public virtual Friendliness Friendliness1 { get; set; }
        public virtual Health Health1 { get; set; }
        public virtual Training Training1 { get; set; }
    }
}
