//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public string locationName { get; set; }
        public Nullable<int> rating1 { get; set; }
        public string review { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
