//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int breedID { get; set; }
        public int overall { get; set; }
        public int easiness { get; set; }
        public int intelligence { get; set; }
        public int mouthiness { get; set; }
        public int preyDrive { get; set; }
        public int bark { get; set; }
        public int wanderlust { get; set; }
    
        public virtual OverallInformation OverallInformation { get; set; }
    }
}
